# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWind.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 732)
        MainWindow.setStyleSheet("font: 16pt \"华文彩云\";\n"
"border-image: url(haha.jpg);\n"
"/*border-image:none;*/\n"
"border-radius: 10px;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.toolButton_5 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_5.setStyleSheet("color:rgb(62, 62, 62);\n"
"font: 40pt \"方正舒体\";\n"
"border-image:none;\n"
"")
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_3.addWidget(self.toolButton_5, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setMinimumSize(QtCore.QSize(291, 71))
        self.toolButton.setMaximumSize(QtCore.QSize(582, 142))
        self.toolButton.setStyleSheet("QFont font(\"Courier\", 20, QFont::Normal, false);\n"
"")
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("border-image:none;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("con1.png"))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.toolButton_4 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_4.setMinimumSize(QtCore.QSize(291, 71))
        self.toolButton_4.setMaximumSize(QtCore.QSize(582, 142))
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("border-image:none;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("con4.png"))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setMinimumSize(QtCore.QSize(291, 71))
        self.toolButton_3.setMaximumSize(QtCore.QSize(582, 142))
        self.toolButton_3.setStyleSheet("font: 16pt \"华文彩云\";")
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("border-image:none;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("con3.png"))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("border-image:none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("con2.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setMinimumSize(QtCore.QSize(291, 71))
        self.toolButton_2.setMaximumSize(QtCore.QSize(582, 142))
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_5.setText(_translate("MainWindow", "考生行为识别系统"))
        self.toolButton.setText(_translate("MainWindow", "实时监测"))
        self.toolButton_4.setText(_translate("MainWindow", "后台审查"))
        self.toolButton_3.setText(_translate("MainWindow", "去模糊"))
        self.toolButton_2.setText(_translate("MainWindow", "视频回溯"))
        self.action2.setText(_translate("MainWindow", "2"))
